// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/guidr/Dashboard.tsx": () => import("../components/mockups/guidr/Dashboard.tsx"),
  "./components/mockups/guidr/Interests.tsx": () => import("../components/mockups/guidr/Interests.tsx"),
  "./components/mockups/guidr/Landing.tsx": () => import("../components/mockups/guidr/Landing.tsx"),
  "./components/mockups/guidr/Lesson.tsx": () => import("../components/mockups/guidr/Lesson.tsx"),
  "./components/mockups/guidr/Login.tsx": () => import("../components/mockups/guidr/Login.tsx"),
  "./components/mockups/guidr/Onboarding.tsx": () => import("../components/mockups/guidr/Onboarding.tsx"),
  "./components/mockups/guidr/Opportunities.tsx": () => import("../components/mockups/guidr/Opportunities.tsx"),
  "./components/mockups/guidr/OpportunityDetail.tsx": () => import("../components/mockups/guidr/OpportunityDetail.tsx"),
  "./components/mockups/guidr/Profile.tsx": () => import("../components/mockups/guidr/Profile.tsx"),
  "./components/mockups/guidr/Saved.tsx": () => import("../components/mockups/guidr/Saved.tsx"),
  "./components/mockups/guidr/Signup.tsx": () => import("../components/mockups/guidr/Signup.tsx"),
  "./components/mockups/guidr/Tutor.tsx": () => import("../components/mockups/guidr/Tutor.tsx"),
  "./components/mockups/guidr-admin/Lessons.tsx": () => import("../components/mockups/guidr-admin/Lessons.tsx"),
  "./components/mockups/guidr-admin/Login.tsx": () => import("../components/mockups/guidr-admin/Login.tsx"),
  "./components/mockups/guidr-admin/Opportunities.tsx": () => import("../components/mockups/guidr-admin/Opportunities.tsx")
};
