export const EGYPTIAN_GOVERNORATES = [
  "Cairo",
  "Giza",
  "Alexandria",
  "Qalyubia",
  "Sharqia",
  "Dakahlia",
  "Gharbia",
  "Monufia",
  "Beheira",
  "Kafr El Sheikh",
  "Damietta",
  "Port Said",
  "Ismailia",
  "Suez",
  "North Sinai",
  "South Sinai",
  "Faiyum",
  "Beni Suef",
  "Minya",
  "Asyut",
  "Sohag",
  "Qena",
  "Luxor",
  "Aswan",
  "Red Sea",
  "New Valley",
  "Matrouh",
] as const;

export const MVP_CATEGORIES = [
  "Competitions",
  "Summer Programs",
  "Research Programs",
  "Events",
  "Exchange Programs",
  "Volunteering",
  "University Clubs & Communities",
  "Scholarships",
] as const;

/** Subject-area interests for student profiles (not opportunity categories). */
export const STUDENT_INTERESTS = [
  "Computer Science",
  "Engineering",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Medicine & Healthcare",
  "Business & Entrepreneurship",
  "Economics & Finance",
  "Research",
  "Leadership",
  "Public Speaking & Debate",
  "Law & Politics",
  "Arts & Design",
  "Media & Content Creation",
  "Writing & Literature",
  "Languages",
  "Social Impact & Volunteering",
  "Environment & Sustainability",
  "Sports & Fitness",
  "Music & Performing Arts",
  "History",
] as const;
